# Generated by Django 3.0.8 on 2020-07-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyImage', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=15)),
                ('bedrooms', models.CharField(blank=True, max_length=15)),
                ('bathrooms', models.CharField(blank=True, max_length=15)),
                ('yearBuilt', models.CharField(blank=True, max_length=15)),
                ('squareFeet', models.CharField(blank=True, max_length=15)),
                ('zillowUrl', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
